logging:
  level:
    com.mikeshaggy.backend: INFO
    org.springframework.security: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
    org.hibernate.SQL: ${LOCAL_HIBERNATE_SQL_LOG_LEVEL:WARN}
    org.hibernate.orm.jdbc.bind: ${LOCAL_HIBERNATE_BIND_LOG_LEVEL:WARN}